name: Build and Package Python Project with Python 3.11

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  build-on-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Check out repository code
        with:
          submodules: true

      - name: Install Python 3.11 (Linux)
        run: |
          sudo apt-get update
          sudo add-apt-repository ppa:deadsnakes/ppa -y
          sudo apt-get install -y python3.11 python3.11-dev python3.11-distutils python3.11-venv
          python3.11 -m pip install --upgrade pip

      - name: Install CMake and Make (Linux)
        run: sudo apt-get install -y cmake make

      - name: Build poker-eval (Linux)
        run: |
          cd poker-eval
          mkdir -p build
          cd build
          cmake ..
          make
          cd ../..

      - name: Build pypoker-eval (Linux)
        run: |
          mkdir -p build
          cd build
          cmake ..
          make

  build-on-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        name: Check out repository code
        with:
          submodules: true

      - name: Install Python 3.11 (macOS)
        run: |
          brew install python@3.11
          echo 'export PATH="/usr/local/opt/python@3.11/bin:$PATH"' >> $GITHUB_ENV
          python3.11 -m pip install --upgrade pip

      - name: Install CMake and Make (macOS)
        run: brew install cmake make

      - name: Build poker-eval (macOS)
        run: |
          cd poker-eval
          mkdir -p build
          cd build
          cmake ..
          make
          cd ../..

      - name: Build pypoker-eval (macOS)
        run: |
          mkdir -p build
          cd build
          cmake ..
          make

  build-on-macos-arm:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
        name: Check out repository code
        with:
          submodules: true

      - name: Install Python 3.11 (macOS ARM)
        run: |
          arch -arm64 brew install python@3.11
          echo 'export PATH="/opt/homebrew/opt/python@3.11/bin:$PATH"' >> $GITHUB_ENV
          arch -arm64 python3.11 -m pip install --upgrade pip

      - name: Install CMake and Make (macOS ARM)
        run: arch -arm64 brew install cmake make

      - name: Build poker-eval (macOS ARM)
        run: |
          cd poker-eval
          mkdir -p build
          cd build
          arch -arm64 cmake ..
          arch -arm64 make
          cd ../..

      - name: Build pypoker-eval (macOS ARM)
        run: |
          mkdir -p build
          cd build
          arch -arm64 cmake ..
          arch -arm64 make

  build-on-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        name: Check out repository code
        with:
          submodules: true

      - name: Install Python 3.11 (Windows)
        run: |
          choco install python --version=3.11.0 -y
          echo "C:\Python311\Scripts;C:\Python311" | Set-Content -Path $env:GITHUB_PATH -Encoding utf8 -Append
          python -m pip install --upgrade pip

      - name: Install CMake
        run: choco install cmake -y

      - name: Build poker-eval (Windows)
        run: |
          cd poker-eval
          mkdir -p build
          cd build
          cmake .. -G "Visual Studio 16 2019"
          cmake --build .
          cd ../..

      - name: Build pypoker-eval (Windows)
        run: |
          mkdir -p build
          cd build
          cmake .. -G "Visual Studio 16 2019"
          cmake --build .
