name: Build and Package Python Project with Python 3.11

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  build-on-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name: Check out repository code
      with:
        submodules: true

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: "3.11"
        activate-environment: fpdb311

    - name: Install Python development headers
      shell: bash -l {0}
      run: |
          conda install -y python=3.11
          sudo apt-get update
          sudo apt-get install -y python3-dev
    - name: Build poker-eval (Linux)
      shell: bash -l {0}
      run: |
        cd poker-eval
        mkdir -p build
        cd build
        cmake .. -DCMAKE_POSITION_INDEPENDENT_CODE=ON
        make
        cd ../..


    - name: Build pypoker-eval (Linux)
      shell: bash -l {0}
      run: |
          sudo apt-get update
          sudo apt-get install -y python3-dev
          mkdir -p build
          cd build
          cmake -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON ..
          cmake --build . --verbose
          cd ..
          find . -name "*pokereval*.so"
          cp build/*pokereval*.so _pokereval_3_11.so || true

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: pokereval-linux
        path: _pokereval_3_11.so