name: Build and Package Python Project with Python 3.11

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  build-on-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name: Check out repository code
      with:
        submodules: true
    - name: Set up Anaconda
      run: |
        wget https://repo.anaconda.com/archive/Anaconda3-2023.07-1-Linux-x86_64.sh -O anaconda.sh
        bash anaconda.sh -b -p $HOME/anaconda
        echo "$HOME/anaconda/bin" >> $GITHUB_PATH
    - name: Create and activate conda environment
      run: |
        source $HOME/anaconda/bin/activate
        conda create -n fpdb311 python=3.11 -y
        source $HOME/anaconda/bin/activate fpdb311
        conda activate fpdb311
    - name: Install CMake and Make (Linux)
      run: sudo apt-get install -y cmake make
    - name: Build poker-eval (Linux)
      run: |
        source $HOME/anaconda/bin/activate fpdb311
        cd poker-eval
        mkdir -p build
        cd build
        cmake .. -DCMAKE_POSITION_INDEPENDENT_CODE=ON
        make
        cd ../..
    - name: Build pypoker-eval (Linux)
      run: |
        source $HOME/anaconda/bin/activate fpdb311
        mkdir -p build
        cd build
        cmake -DPython3_EXECUTABLE=$(which python) -DPython3_INCLUDE_DIR=$(python -c "from sysconfig import get_paths as gp; print(gp()['include'])") -DPython3_LIBRARY=$(python -c "from sysconfig import get_config_var as gcv; print(gcv('LIBDIR') + '/libpython3.11.so')") ..
        make
        cd ..
        cp build/pypokereval.so _pokereval_3_11.so
