name: Build and Package Python Project with Python 3.11

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  build-on-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name: Check out repository code
      with:
        submodules: true

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: "3.11"
        activate-environment: fpdb311

    - name: Install dependencies
      shell: bash -l {0}
      run: |
        conda install -y cmake make
        sudo apt-get update
        sudo apt-get install -y libbz2-dev

    - name: Build poker-eval (Linux)
      shell: bash -l {0}
      run: |
        cd poker-eval
        mkdir -p build
        cd build
        cmake .. -DCMAKE_POSITION_INDEPENDENT_CODE=ON
        make
        cd ../..

    - name: Build pypoker-eval (Linux)
      shell: bash -l {0}
      run: |
          conda info
          which python
          python --version
          python -c "import sys; print(sys.executable)"
          python -c "import sysconfig; print(sysconfig.get_paths())"
          mkdir -p build
          cd build
          cmake -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON \
                -DPython3_EXECUTABLE=$(which python) \
                -DPython3_INCLUDE_DIR=$(python -c "import sysconfig; print(sysconfig.get_path('include'))") \
                -DPython3_LIBRARY=$(python -c "import sysconfig; print(sysconfig.get_config_var('LIBDIR') + '/libpython' + sysconfig.get_config_var('LDVERSION') + '.so')") \
                ..
          cmake --build . --verbose
          cd ..
          find . -name "*pokereval*.so"
          cp build/*pokereval*.so _pokereval_3_11.so || true

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: pokereval-linux
        path: _pokereval_3_11.so