name: Build and Package Python Project with Python 3.11

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3.11 python3.11-dev

      - name: Configure, Build and Test
        run: |
          mkdir -p build
          cd build
          cmake -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON ..
          cmake --build . --verbose
          cd ..
          find . -name "*pokereval*.so"
          cp build/*pokereval*.so _pokereval_3_11.so || true
        
  build-linux-arm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker buildx create --use
          docker buildx build --platform linux/arm64 -t my-arm-build .

      - name: Run Docker container
        run: |
          docker run --rm my-arm-build /bin/sh -c "
          mkdir build &&
          cd build &&
          cmake .. &&
          cmake --build . &&
          ctest --output-on-failure"

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Configure, Build and Test
        shell: pwsh
        run: |
          $pythonRoot = $env:pythonLocation
          $pythonExe = Join-Path $pythonRoot "python.exe"
          $pythonLib = Join-Path $pythonRoot "libs\python311.lib"
          $pythonInclude = Join-Path $pythonRoot "include"
          
          mkdir build
          cd build
          cmake .. -G "Visual Studio 17 2022" -A x64 -DPYTHON_EXECUTABLE="$pythonExe" -DPYTHON_LIBRARY="$pythonLib" -DPYTHON_INCLUDE_DIR="$pythonInclude"
          cmake --build . --config Release --verbose
          cd ..
          
          # Copier le fichier de sortie pour une utilisation ultérieure
          Get-ChildItem -Recurse -Filter "*pokereval*.pyd" | Copy-Item -Destination _pokereval_3_11.pyd -Force
    env:
      PYTHON_ROOT: ${{ secrets.PYTHON_ROOT }}

  build-on-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cmake
    - name: Build poker-eval (macOS)
      run: |
        cd poker-eval
        mkdir build
        cd build
        cmake .. -DCMAKE_POSITION_INDEPENDENT_CODE=ON
        make
        cd ../..
    - name: Build pypoker-eval (macOS)
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON ..
        cmake --build . --verbose
        cd ..
        find . -name "*pokereval*.so" -exec cp {} _pokereval_3_11.so \; || true
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: pokereval-macos
        path: _pokereval_3_11.so

  build-on-macos-arm:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cmake
    - name: Build poker-eval (macOS ARM)
      run: |
        cd poker-eval
        mkdir build
        cd build
        cmake .. -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DCMAKE_OSX_ARCHITECTURES=arm64
        make
        cd ../..
    - name: Build pypoker-eval (macOS ARM)
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCMAKE_OSX_ARCHITECTURES=arm64 ..
        cmake --build . --verbose
        cd ..
        find . -name "*pokereval*.so" -exec cp {} _pokereval_3_11.so \; || true
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: pokereval-macos-arm
        path: _pokereval_3_11.so